; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:esp32dev]
platform = espressif32
framework = arduino
board = esp32dev
# if simulation is true, use 9600 baud rate, else use 115200
monitor_speed = 9600
build_flags =
  -D CONFIG_BLINK_GPIO=2
  -D BAUD_RATE=${env.monitor_speed}
check_tool = clangtidy, cppcheck
check_flags =
  clangtidy: --checks=*,-modernize-use-trailing-return-type
  cppcheck: --enable=warning,style

lib_deps =
  ESP32Async/ESPAsyncWebServer@^3.7.4
  ESP32Async/AsyncTCP@^3.3.8