; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32doit-devkit-v1

[common]
monitor_speed = 115200
framework = arduino
lib_deps =
    askuric/Simple FOC@^2.3.4
    Wire
    SPI
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D PIO_FRAMEWORK_ARDUINO_NANOLIB_FLOAT_PRINTF
    -D PIO_FRAMEWORK_ARDUINO_USB_HIGHSPEED_FULLMODE
    -D BAUD_RATE=${common.monitor_speed}
build_src_filter =
    ${env.build_src_filter}
    -<tools/*.cpp>
    -<tests/*.cpp>
lib_archive = false

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
build_src_filter = 
    ${common.build_src_filter}
build_flags = ${common.build_flags}
monitor_speed = ${common.monitor_speed}
framework = ${common.framework}
lib_deps =
    ${common.lib_deps}
    nRF24
    nrf24/RF24@^1.4.9
lib_archive = ${common.lib_archive}

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
build_src_filter = 
    ${common.build_src_filter}
    -<main.cpp>
    +<tests/malha_aberta.cpp>
build_flags = ${common.build_flags}
monitor_speed = ${common.monitor_speed}
framework = ${common.framework}
lib_deps = ${common.lib_deps}
lib_archive = ${common.lib_archive}


[env:STM32_bluepill]
platform = ststm32
board = bluepill_f103c8
debug_tool = stlink
upload_protocol = stlink
upload_flags = -c set CPUTAPID 0x2ba01477
build_src_filter = 
    ${common.build_src_filter}
    -<main.cpp>
    +<tests/malha_fechada.cpp>
build_flags = ${common.build_flags}
monitor_speed = ${common.monitor_speed}
framework = ${common.framework}
lib_deps = ${common.lib_deps}
lib_archive = ${common.lib_archive}
