#pragma once

#include <driver/gpio.h>

#ifdef ARDUINO_ESP32_DEV

#define BLINK_GPIO GPIO_NUM_2

// M0
#define PIN_MOTOR_FRONT_LEFT_PWM GPIO_NUM_27
#define PIN_MOTOR_FRONT_LEFT_DIR GPIO_NUM_25
// M1
#define PIN_MOTOR_BACK_LEFT_PWM GPIO_NUM_14
#define PIN_MOTOR_BACK_LEFT_DIR GPIO_NUM_26
// M2
#define PIN_MOTOR_BACK_RIGHT_PWM GPIO_NUM_12
#define PIN_MOTOR_BACK_RIGHT_DIR GPIO_NUM_32
// M3
#define PIN_MOTOR_FRONT_RIGHT_PWM GPIO_NUM_13
#define PIN_MOTOR_FRONT_RIGHT_DIR GPIO_NUM_33

#endif  // ARDUINO_ESP32_DEV
